
export const SET_MODULE_STARSHIP_NEXT_PAGE = 'SET_MODULE_STARSHIP_NEXT_PAGE';
export const SET_MODULE_STARSHIP_COUNT = 'SET_MODULE_STARSHIP_COUNT';


export const INIT_STARSHIPS_CACHE = 'INIT_STARSHIPS_CACHE';

export const SET_STARSHIPS = 'FETCH_STARSHIPS';
export const FETCH_STARSHIPS = 'FETCH_STARSHIPS';
export const FETCH_ONE_STARSHIP = 'FETCH_ONE_STARSHIP';

export const SET_FETCH_STATUS_LOADING = 'SET_FETCH_STATUS_LOADING';
export const SET_FETCH_STATUS_SUCCESS = 'SET_FETCH_STATUS_SUCCESS';
export const SET_FETCH_STATUS_ERROR = 'SET_FETCH_STATUS_ERROR';
