export const SET_PREVIOUS_FETCH_VIA_CACHE = 'SET_PREVIOUS_FETCH_VIA_CACHE';

export const SET_MODULE_STARSHIP_NEXT_PAGE = 'SET_MODULE_STARSHIP_NEXT_PAGE';
export const SET_MODULE_STARSHIP_COUNT = 'SET_MODULE_STARSHIP_COUNT';

export const SET_STARSHIPS = 'FETCH_STARSHIPS';
export const FETCH_STARSHIPS = 'FETCH_STARSHIPS';
export const SET_STARSHIP_BY_ID = 'SET_STARSHIP_BY_ID';
export const FETCH_ONE_STARSHIP = 'FETCH_ONE_STARSHIP';


export const SET_FETCH_STATUS_LOADING = 'SET_FETCH_STATUS_LOADING';
export const SET_FETCH_STATUS_SUCCESS = 'SET_FETCH_STATUS_SUCCESS';
export const SET_FETCH_STATUS_ERROR = 'SET_FETCH_STATUS_ERROR';

export const FETCH_STARSHIPS_SCHEMA = 'FETCH_STARSHIPS_SCHEMA';
export const SET_STARSHIPS_SCHEMA = 'SET_STARSHIPS_SCHEMA';
export const SET_STARSHIPS_CACHE = 'SET_STARSHIPS_CACHE';
export const SET_PAGE_STARSHIPS_CACHE = 'SET_PAGE_STARSHIPS_CACHE';
